name: ☑️ Tasks
description: 기능 구현 후 검증을 위해 테스트를 요청할 때 사용합니다.
title: "☑️ Tasks: "
labels: ["Tasks"]
body:
  - type: textarea
    id: what-to-test
    attributes:
      label: ✅ 진행할 일정
      placeholder: 
    validations:
      required: true

  - type: textarea
    id: test-checklist
    attributes:
      label: 🧾 테스트 체크리스트
      placeholder: |
        - [ ] 
        - [ ] 
        - [ ] 
      value: "- [ ] "
    validations:
      required: true